In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/website-traffic-analysis/traffic.csv
/kaggle/input/customer-behavior-analysis/ecommerce_customer_data_large.csv
/kaggle/input/customer-behavior-analysis/ecommerce_customer_data_custom_ratios.csv

In [2]:
df = pd.read_csv("/kaggle/input/customer-behavior-analysis/ecommerce_customer_data_large.csv")
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

# Customer Behavior Analysis for Alfido Tech

## Task 1 Objective  
Analyze customer transactions to identify segments, purchase patterns, and churn risks.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [4]:
df = pd.read_csv("/kaggle/input/customer-behavior-analysis/ecommerce_customer_data_large.csv")
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

In [5]:
import os

os.listdir("/kaggle/input")

['website-traffic-analysis', 'customer-behavior-analysis']

In [6]:
import os
os.listdir("/kaggle/input")

['website-traffic-analysis', 'customer-behavior-analysis']

In [7]:
import os

os.listdir("/kaggle/input/customer-behavior-analysis")

['ecommerce_customer_data_large.csv',
 'ecommerce_customer_data_custom_ratios.csv']

In [8]:
import pandas as pd

df = pd.read_csv("/kaggle/input/customer-behavior-analysis/ecommerce_customer_data_large.csv")

df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202618 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB

In [10]:
df.describe()

,Customer ID,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Age,Churn
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,202618.000000,250000.000000,250000.00000
mean,25017.632092,254.742724,3.004936,2725.385196,43.798276,0.500824,43.798276,0.20052
std,14412.515718,141.738104,1.414737,1442.576095,15.364915,0.500001,15.364915,0.40039
min,1.000000,10.000000,1.000000,100.000000,18.000000,0.000000,18.000000,0.00000
25%,12590.000000,132.000000,2.000000,1476.000000,30.000000,0.000000,30.000000,0.00000
50%,25011.000000,255.000000,3.000000,2725.000000,44.000000,1.000000,44.000000,0.00000
75%,37441.250000,377.000000,4.000000,3975.000000,57.000000,1.000000,57.000000,0.00000
max,50000.000000,500.000000,5.000000,5350.000000,70.000000,1.000000,70.000000,1.00000

# Customer Behavior Analysis – Task 1

## 1. Introduction
This notebook analyzes customer behavior data to understand purchasing patterns, engagement, and trends using Kaggle dataset.

## 2. Dataset Loading
We load the ecommerce customer dataset and explore its structure.

## 3. Data Overview
We inspect columns, data types, and summary statistics.

In [11]:
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47382
Customer Name                0
Age                          0
Gender                       0
Churn                        0
dtype: int64

In [12]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [13]:
df.describe()

,Customer ID,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Age,Churn
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,202618.000000,250000.000000,250000.00000
mean,25017.632092,254.742724,3.004936,2725.385196,43.798276,0.500824,43.798276,0.20052
std,14412.515718,141.738104,1.414737,1442.576095,15.364915,0.500001,15.364915,0.40039
min,1.000000,10.000000,1.000000,100.000000,18.000000,0.000000,18.000000,0.00000
25%,12590.000000,132.000000,2.000000,1476.000000,30.000000,0.000000,30.000000,0.00000
50%,25011.000000,255.000000,3.000000,2725.000000,44.000000,1.000000,44.000000,0.00000
75%,37441.250000,377.000000,4.000000,3975.000000,57.000000,1.000000,57.000000,0.00000
max,50000.000000,500.000000,5.000000,5350.000000,70.000000,1.000000,70.000000,1.00000

In [14]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(df['column_name'], kde=True)
plt.show()

KeyError: 'column_name'

In [ ]:
# Step 4: Data Cleaning

# 1. Check for missing values
print("Missing Values in Each Column:")
print(df.isnull().sum())

# 2. Handle missing values
# For numeric columns, fill missing with median
numeric_cols = df.select_dtypes(include=['int64','float64']).columns
for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

# For categorical columns, fill missing with mode
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# 3. Check for duplicates
print("\nNumber of duplicate rows:", df.duplicated().sum())

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# 4. Verify changes
print("\nData after cleaning:")
print(df.info())
print(df.head())

In [ ]:
# Step 5: Exploratory Data Analysis (EDA)
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Summary statistics of numerical columns
print("Numerical Columns Summary:")
print(df.describe())

# 2. Distribution of numerical features
numeric_cols = df.select_dtypes(include=['int64','float64']).columns
for col in numeric_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.show()

# 3. Count plots for categorical features
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    plt.figure(figsize=(8,4))
    sns.countplot(x=col, data=df, order=df[col].value_counts().index)
    plt.title(f'Count of {col}')
    plt.xticks(rotation=45)
    plt.show()

# 4. Correlation heatmap for numerical features
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

In [ ]:
# Step 6: Customer Behavior Insights

# 1. Top 10 most purchased products
top_products = df['product_name'].value_counts().head(10)
print("Top 10 Products:")
print(top_products)

plt.figure(figsize=(10,5))
sns.barplot(x=top_products.values, y=top_products.index, palette='viridis')
plt.title("Top 10 Purchased Products")
plt.xlabel("Number of Purchases")
plt.ylabel("Product Name")
plt.show()

# 2. Most popular product categories
top_categories = df['product_category'].value_counts()
print("\nProduct Categories:")
print(top_categories)

plt.figure(figsize=(8,4))
sns.barplot(x=top_categories.index, y=top_categories.values, palette='magma')
plt.title("Product Category Counts")
plt.xticks(rotation=45)
plt.xlabel("Category")
plt.ylabel("Number of Purchases")
plt.show()

# 3. Customer purchase trends over time
# Ensure the order_date column is datetime type
df['order_date'] = pd.to_datetime(df['order_date'])

# Monthly purchase trend
monthly_trends = df.groupby(df['order_date'].dt.to_period('M')).size()
monthly_trends.index = monthly_trends.index.to_timestamp()

plt.figure(figsize=(10,5))
monthly_trends.plot(marker='o')
plt.title("Monthly Purchase Trend")
plt.xlabel("Month")
plt.ylabel("Number of Orders")
plt.grid(True)
plt.show()

In [ ]:
print(df.columns)

In [ ]:
top_products = df['Product_Name'].value_counts().head(10)

In [ ]:
print(df.columns)

In [ ]:
print(df['Product_Name'].value_counts().head(10))

In [ ]:
# Step 6: Customer Behavior Insights (Corrected for your dataset)

# 1. Most popular product categories
top_categories = df['Product Category'].value_counts().head(10)
print("Top 10 Product Categories:")
print(top_categories)

plt.figure(figsize=(10,5))
sns.barplot(x=top_categories.values, y=top_categories.index, palette='viridis')
plt.title("Top 10 Product Categories")
plt.xlabel("Number of Purchases")
plt.ylabel("Category")
plt.show()

# 2. Customer purchase trends over time
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])

monthly_trends = df.groupby(df['Purchase Date'].dt.to_period('M')).size()
monthly_trends.index = monthly_trends.index.to_timestamp()

plt.figure(figsize=(10,5))
monthly_trends.plot(marker='o')
plt.title("Monthly Purchase Trend")
plt.xlabel("Month")
plt.ylabel("Number of Orders")
plt.grid(True)
plt.show()

In [ ]:
# Step 7: Correlation & Feature Analysis

# Select numeric columns for correlation
numeric_cols = ['Product Price', 'Quantity', 'Total Purchase Amount', 'Customer Age', 'Returns', 'Age']

# 1. Correlation matrix
corr_matrix = df[numeric_cols].corr()
print("Correlation Matrix:")
print(corr_matrix)

# 2. Visualize correlation heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap of Numeric Features")
plt.show()

# 3. Scatter plots for interesting relationships
plt.figure(figsize=(6,4))
sns.scatterplot(x='Quantity', y='Total Purchase Amount', data=df)
plt.title("Quantity vs Total Purchase Amount")
plt.xlabel("Quantity")
plt.ylabel("Total Purchase Amount")
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(x='Customer Age', y='Total Purchase Amount', data=df)
plt.title("Customer Age vs Total Purchase Amount")
plt.xlabel("Customer Age")
plt.ylabel("Total Purchase Amount")
plt.show()

In [ ]:
# Step 8: Summary & Recommendations

# Optional: print some key observations
print("Step 8: Key Observations from Customer Behavior Analysis\n")

# Example insights based on your dataset
print("1. Top product categories are:", top_categories.index.tolist())
print("2. Purchase trends show peaks in certain months (check monthly trend graph).")
print("3. Quantity is positively correlated with Total Purchase Amount.")
print("4. Customer Age has some impact on total purchase behavior (see scatter plot).")
print("5. Returns and churn may indicate areas for improvement in customer satisfaction.\n")

print("Recommendations:")
print("• Focus marketing efforts on top product categories to maximize sales.")
print("• Offer targeted promotions during months with lower purchases.")
print("• Analyze returns and churn data to improve customer retention.")
print("• Personalize offers based on customer age groups and buying patterns.")

# Summary & Recommendations

**Key Insights:**
- The most purchased product categories are [...top categories...].
- Monthly purchase trends show peak sales in [...months...].
- Quantity purchased is strongly correlated with Total Purchase Amount.
- Customer age affects purchasing behavior slightly.
- Returns and churn rates indicate potential areas for improvement.

**Recommendations:**
- Focus on marketing top-selling categories.
- Plan promotional campaigns during slow months.
- Address returns and churn to improve customer satisfaction.
- Personalize offers based on age and purchase trends.